### ISSUE TITLE
Can't join discord

### ISSUE THREAD

**Issue by flashlink12** [LoukaMB/SynapseX#104]
For some reason I am not on the discord anymore ( I was in) and now I can't join.

**Comment by djmanohsick1** [comment]
I can’t find it and I somehow left lol

**Comment by 3xjn** [comment]
You can join sir meme's discord ask the synapse admins for an invite.
https://discord.me/realsirmeme

**Comment by flashlink12** [comment]
I think their discord got banned. I already got in when updated synapse.
