### ISSUE TITLE
synapse keep saying "failled to download bootstrapper files. Please check your anti-virus software". Even though I turned off all the anti virus

### ISSUE THREAD

**Issue by BruhSendMeHelp** [LoukaMB/SynapseX#131]
I turned off all the anti-virus software and also whitelisted, redownload, restarts, shutdowns. All of them don't work even after i did everything i can think of. please send help!
![an](https://user-images.githubusercontent.com/62160314/76665304-3d1a9800-6555-11ea-96f7-c41de216664d.jpg)
![sad](https://user-images.githubusercontent.com/62160314/76665305-3f7cf200-6555-11ea-903d-7ac1fc7bafa8.jpg)
![NOO](https://user-images.githubusercontent.com/62160314/76665307-4146b580-6555-11ea-822b-d710e885e028.jpg)

and it didnt even load anything but just the antivirus screen
https://media.giphy.com/media/ZAr8LmjlgpZoTsaCDq/giphy.gif

**Comment by BruhSendMeHelp** [comment]
pls help, i really need to use synapse !!!

**Comment by ParkerDMoore** [comment]
I downloaded today and it is doing the same thing to me, and I also turned my antivirus off. Please Help

**Comment by GhostXS** [comment]
Same, Idrk what happened. I'm hoping its not from my end because I've been trying for 2 days to fix this problem and nothing i find worked.

If an admin can get in contact with me or a helper that would be really appreciated because I don't want to have spent 20 dollars and not being able to do anything with what I bought.

**Comment by Wolfgalax** [comment]
Synapse X Been saying "failed to download bootstrapper files. Please check your Anti-virus Software" i tried everything I still can't get it to work! Is it broken? I have my anti virus off and my windows fire wall off! is there any fixes?
