### ISSUE TITLE
"Failed to download UI files. Please check your anti-virus sofware". I did turn off every anti-virus but it still say the same thing.

### ISSUE THREAD

**Issue by BruhSendMeHelp** [LoukaMB/SynapseX#153]
After the new UI come, my synapse refuse to work, a week ago i did post a similar issues to this, here is the pictures.

![syna](https://user-images.githubusercontent.com/62160314/77584324-9ae1a500-6eb0-11ea-900f-94b8818e55b1.jpg)

![an](https://user-images.githubusercontent.com/62160314/77455736-42cf7380-6dc8-11ea-90db-9e7b0e4104c0.jpg)
![sad](https://user-images.githubusercontent.com/62160314/77455746-44993700-6dc8-11ea-8b53-d7dc2c03f15e.jpg)

**Comment by BruhSendMeHelp** [comment]
Also i wonder how do i join their discord, i have synapse and people keep saying it's automatic but i don't think i ever join synapse discord before.

**Comment by MrEmulate** [comment]
I have this issue but it opens synapse instead.

**Comment by IsntLovely** [comment]
Same Problem complete eliminated the antivirus still doesn't work :C

**Comment by Jmodel10** [comment]
im having a problem too but it is a different problem
