### ISSUE TITLE
error downloading synapse even after disabling antivirus

### ISSUE THREAD

**Issue by AviaMako** [LoukaMB/SynapseX#206]
Synapse was working perfectly until a few days ago when i got the error "Failed to download bootstrapper files. Please check your antivirus software." My antivirus is off so I dont know why this is happening, please help.

**Comment by chrissie1234** [comment]
I got the same issue. Using ProtonVPN didn't resolve the issue.

**Comment by yourbtv** [comment]
Same

**Comment by yourbtv** [comment]
I used a vpn and still no luck

**Comment by UhCharles** [comment]
yes same bro

**Comment by yourbtv** [comment]
I figured out how to fix

**Comment by yourbtv** [comment]
get proton vpn for free and shut off all windows setting

**Comment by yourbtv** [comment]
then exclude the folder

**Comment by yourbtv** [comment]
go to this link this is support forum [https://docs.google.com/document/d/1cPYeVVJiVilvnr80crDe4apRYHuwMlz0w17dsPuV3fI/edit#](url)

**Comment by AviaMako** [comment]
thanks when i got the vpn it worked
