### ISSUE TITLE
Unable to use synapse

### ISSUE THREAD

**Issue by RubiksMaster3x3** [LoukaMB/SynapseX#234]
I am unable to use synapse x after purchasing because every time I try to load it up, I get an error that it hasn't been updated and I should wait. I waited, and still nothing. What should I do?

**Comment by 2nu4** [comment]
That's for everyone. Synapse is taking time to update with Roblox to ensure our safety there should be more information about when it's coming back up in the discord but I'd say it'll be up in an hour or two.

**Comment by REBLEDANGER** [comment]
do you know what’s the discord link because i can’t find it anymore
