### ISSUE TITLE
"failed to download bootstrapper files" and the error code (4)

### ISSUE THREAD

**Issue by CleanVerse** [LoukaMB/SynapseX#297]
I have tried everything i could think of, I added every file to the exclusions, I disabled ALL my anti viruses, and then I restarted my computer tried opening Synapse still got the error message then I tried redownloading it and still got the same message.

Contact me at contagiousfps@gmail.com

**Comment by ChocolateRain6903** [comment]
Has anyone found a fix to this? I have the same issue.
