### ISSUE TITLE
Synapse X failed to download launcher file. please check your antivirus software. 

### ISSUE THREAD

**Issue by nobykenobie** [LoukaMB/SynapseX#377]
Anybody know how to fix this error  failed to download launcher file. please check your antivirus software.

**Comment by ijsbeerr** [comment]
most likely your antivirus, make sure you made an exclusion to the Synapse X Folder

**Comment by KINGYSB** [comment]
**Hi @nobykenobie,**
To resolve this issue you should see this [documentation](https://x.synapse.to/docs/install/whitelist_av.html) for assistance on how to whitelist Synapse from your antivirus software.

- This video should also be somewhat helpful to resolve your antivirus issue. https://youtu.be/0GPW2p6TsPo

**Comment by nobykenobie** [comment]
I figured it out last week should of told you. It was that i just whitelisted synapse and not the folder. 


Thank you
