### ISSUE TITLE
Inject Bans on Island Royale

### ISSUE THREAD

**Issue by juniorjacob** [LoukaMB/SynapseX#5]
https://www.roblox.com/games/1320186298/NEW-SEASON-Island-Royale-Beta#!/game-instances

luckily i know the games ac so i can tell you right now whats going wrong, luckily

basically whenever you inject you get banned for code 23, that code is related to roblox's environment having a function changing (checks with getfenv)

basically if you dont put my script in autoexec, you will get banned, which shouldnt have to be the case, please fix

**Comment by juniorjacob** [comment]
Anticheat is in nil instances named with unicode, heres a download link for the current ac

https://mega.nz/#!Hz5X1K5C!qpTMyagad1meMVOnkWwk2XJZBWvt9A3KwJ5t6uF8420

**Comment by 3dsboy08** [comment]
This happens due to the Synapse environment sometimes being inserted into the wrong place. I am working on fixing this.

**Comment by 3dsboy08** [comment]
Fixed with 1.1.1b.
