### ISSUE TITLE
I Purchased Synapse X Steam card $20 but not key received

### ISSUE THREAD

**Issue by dodokorean** [LoukaMB/SynapseX#57]
Hi, I'm korean

I purchased Synapse X the $20 steam card using and tracking code is email send
It is now than 72 hours and still peding no email confirmation or the serial key

Please see attached blow.

My email address is dopio13579@gmail.com

Thanks,

![synapse xXX](https://user-images.githubusercontent.com/31310757/72063717-a8f63f80-331d-11ea-859d-ae69466190f9.PNG)

**Comment by dodokorean** [comment]
@LoukaMB

**Comment by Eleazar9099** [comment]
Hey I have the same problem message me throw this page so I can’t tell me email I payed and it has been 4-5 days and nothing

**Comment by squidkilled99** [comment]
did you get the key yet

**Comment by Eleazar9099** [comment]
On Sat, Jan 11, 2020 at 10:45 AM Eleazar Urias <gaxiolaeleazar99@gmail.com>
wrote:

>
>
> On Sat, Jan 11, 2020 at 10:10 AM Eleazar Urias <gaxiolaeleazar99@gmail.com>
> wrote:
>
>>
>>
>> On Sat, Jan 11, 2020 at 10:09 AM Eleazar Urias <
>> gaxiolaeleazar99@gmail.com> wrote:
>>
>>>
>>>
>>> On Sat, Jan 11, 2020 at 12:52 AM squidkilled99 <notifications@github.com>
>>> wrote:
>>>
>>>> did you get the key yet
>>>>
>>>> No I have not got the key I need the executor for a YouTube video but
>>>> if I don’t get it by tomorrow I’m posting a video of how I just got scammed
>>>> by Synapse
>>>>
>>>
>>> I really love the executor but idk why is this happening or why you guys
>>>> don’t have customer service like  ProtoSmasher like a discord it would be
>>>> really helpful
>>>>
>>> If you guys need evidence that at payed, I don’t have evidence but check
>> with my email I payed with steam card
>>
> I am still waiting for the card it’s not like you guys just keep 20$ you
guys also don’t respond to emails

**Comment by Eleazar9099** [comment]
Man I’m tired of this It says you guys send code in hours but you guys send nothing I want Synapse or my money back I have been waiting way to much and I send you guys emails and not respond that’s so stupid !!!!! Does anybody know how to report the website?

**Comment by dodokorean** [comment]
... I TIRED
7th day, but the serial code is not coming

**Comment by ExDurandalZ** [comment]
U still doesnt got key??

**Comment by NikitaPlayer** [comment]
Synapse is fucking shit
