### ISSUE TITLE
Missing the Io Library?

### ISSUE THREAD

**Issue by Diaxium** [LoukaMB/SynapseX#6]
Recently I was testing somethings and I realized the synapse x doesn't have the Io Library. 
![image](https://user-images.githubusercontent.com/17173359/49701287-6359c700-fb9f-11e8-8734-42a885e299fd.png)

If this is to be added can it have all the regular feature that lua supply's instead of like roblox's where their's is limited. like the io.open, io.read, io.write, and io.flush etc.

**Comment by DocorDerank** [comment]
It was removed because of some functions being dangerous. You can use different functions like print, writefile etc to work around this.

**Comment by 3dsboy08** [comment]
It was removed intentionally for having dangerous functions.
