### ISSUE TITLE
Where My Serial Key? I buy synapse x with steam wallet but doesnt get key

### ISSUE THREAD

**Issue by ExDurandalZ** [LoukaMB/SynapseX#84]
![F4A0DC75-771C-477B-BE5C-3EF31CCE4279](https://user-images.githubusercontent.com/60774782/74014807-02579a00-49c2-11ea-99bc-b66b1e71b1ae.png)
![Uploading C3EF53B5-377C-4CE4-BC30-85C73E4362CD.png…]()

**Comment by ExDurandalZ** [comment]
![Uploading DFE151F9-BEDA-48CD-BFB2-F26803B75727.png…]()

**Comment by ExDurandalZ** [comment]
![47FEE80D-E522-4E91-A574-D07A574B4711](https://user-images.githubusercontent.com/60774782/74015761-d0dfce00-49c3-11ea-88f9-f8959eaf8c75.png)

**Comment by azamaniBoi** [comment]
it is a scam
